### ISSUE TITLE
Add setting language server capabillities

### ISSUE THREAD

**Issue by slarwise** [slarwise/nvim-but-yaml#5]
Something like below. This should keep the default settings and override the provided settings.

```yaml
filetypes:
  yaml:
    language_server:
      server_capabilites:
        DocumentFormattingProvider: true
```
